# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFrame,
    QHBoxLayout, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 640)
        MainWindow.setMinimumSize(QSize(900, 640))
        MainWindow.setStyleSheet(u"background-color: #1a1a2e;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: #1a1a2e;")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.panelKiri = QWidget(self.centralwidget)
        self.panelKiri.setObjectName(u"panelKiri")
        self.panelKiri.setMinimumSize(QSize(340, 0))
        self.panelKiri.setMaximumSize(QSize(340, 16777215))
        self.panelKiri.setStyleSheet(u"QWidget { background-color: #16213e; border-right: 1px solid #1e4d7b; }")
        self.labelTitle = QLabel(self.panelKiri)
        self.labelTitle.setObjectName(u"labelTitle")
        self.labelTitle.setGeometry(QRect(20, 18, 280, 45))
        font = QFont()
        font.setFamilies([u"Impact"])
        font.setPointSize(28)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet(u"color: #00ff87; background: transparent; border: none; letter-spacing: 3px;")
        self.labelSubtitle = QLabel(self.panelKiri)
        self.labelSubtitle.setObjectName(u"labelSubtitle")
        self.labelSubtitle.setGeometry(QRect(22, 60, 250, 18))
        self.labelSubtitle.setStyleSheet(u"color: #a0a0b0; font-size: 10px; background: transparent; border: none; letter-spacing: 2px;")
        self.lineHeader = QFrame(self.panelKiri)
        self.lineHeader.setObjectName(u"lineHeader")
        self.lineHeader.setGeometry(QRect(20, 84, 300, 2))
        self.lineHeader.setStyleSheet(u"background-color: #00c85d; border: none;")
        self.lineHeader.setFrameShape(QFrame.Shape.HLine)
        self.frame = QFrame(self.panelKiri)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(15, 96, 310, 245))
        self.frame.setStyleSheet(u"QFrame { background-color: #0f3460; border-radius: 12px; border: 1px solid #1e4d7b; }")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.labelFormTitle = QLabel(self.frame)
        self.labelFormTitle.setObjectName(u"labelFormTitle")
        self.labelFormTitle.setGeometry(QRect(15, 10, 200, 22))
        self.labelFormTitle.setStyleSheet(u"color: #00c85d; font-size: 10px; font-weight: bold; letter-spacing: 2px; background: transparent; border: none;")
        self.labelInputJudul = QLabel(self.frame)
        self.labelInputJudul.setObjectName(u"labelInputJudul")
        self.labelInputJudul.setGeometry(QRect(15, 38, 130, 16))
        self.labelInputJudul.setStyleSheet(u"color: #a0a0b0; font-size: 10px; background: transparent; border: none;")
        self.inputJudul = QLineEdit(self.frame)
        self.inputJudul.setObjectName(u"inputJudul")
        self.inputJudul.setGeometry(QRect(15, 56, 130, 32))
        self.inputJudul.setStyleSheet(u"QLineEdit { background-color: #0a1930; color: #ffffff; border: 1px solid #1e4d7b; border-radius: 8px; padding: 4px 12px; font-size: 11px; } QLineEdit:focus { border: 1px solid #00c85d; }")
        self.labelInputPenyanyi = QLabel(self.frame)
        self.labelInputPenyanyi.setObjectName(u"labelInputPenyanyi")
        self.labelInputPenyanyi.setGeometry(QRect(160, 38, 130, 16))
        self.labelInputPenyanyi.setStyleSheet(u"color: #a0a0b0; font-size: 10px; background: transparent; border: none;")
        self.inputPenyanyi = QLineEdit(self.frame)
        self.inputPenyanyi.setObjectName(u"inputPenyanyi")
        self.inputPenyanyi.setGeometry(QRect(160, 56, 135, 32))
        self.inputPenyanyi.setStyleSheet(u"QLineEdit { background-color: #0a1930; color: #ffffff; border: 1px solid #1e4d7b; border-radius: 8px; padding: 4px 12px; font-size: 11px; } QLineEdit:focus { border: 1px solid #00c85d; }")
        self.labelInputDurasi = QLabel(self.frame)
        self.labelInputDurasi.setObjectName(u"labelInputDurasi")
        self.labelInputDurasi.setGeometry(QRect(15, 98, 130, 16))
        self.labelInputDurasi.setStyleSheet(u"color: #a0a0b0; font-size: 10px; background: transparent; border: none;")
        self.inputDurasi = QLineEdit(self.frame)
        self.inputDurasi.setObjectName(u"inputDurasi")
        self.inputDurasi.setGeometry(QRect(15, 116, 130, 32))
        self.inputDurasi.setStyleSheet(u"QLineEdit { background-color: #0a1930; color: #ffffff; border: 1px solid #1e4d7b; border-radius: 8px; padding: 4px 12px; font-size: 11px; } QLineEdit:focus { border: 1px solid #00c85d; }")
        self.labelInputGenre = QLabel(self.frame)
        self.labelInputGenre.setObjectName(u"labelInputGenre")
        self.labelInputGenre.setGeometry(QRect(160, 98, 130, 16))
        self.labelInputGenre.setStyleSheet(u"color: #a0a0b0; font-size: 10px; background: transparent; border: none;")
        self.inputGenre = QLineEdit(self.frame)
        self.inputGenre.setObjectName(u"inputGenre")
        self.inputGenre.setGeometry(QRect(160, 116, 135, 32))
        self.inputGenre.setStyleSheet(u"QLineEdit { background-color: #0a1930; color: #ffffff; border: 1px solid #1e4d7b; border-radius: 8px; padding: 4px 12px; font-size: 11px; } QLineEdit:focus { border: 1px solid #00c85d; }")
        self.btnInsertLagu = QPushButton(self.frame)
        self.btnInsertLagu.setObjectName(u"btnInsertLagu")
        self.btnInsertLagu.setGeometry(QRect(15, 165, 280, 42))
        self.btnInsertLagu.setStyleSheet(u"QPushButton { background-color: #00c85d; color: #000000; border-radius: 10px; font-size: 12px; font-weight: bold; letter-spacing: 2px; border: none; } QPushButton:hover { background-color: #00ff87; } QPushButton:pressed { background-color: #009944; }")
        self.frame_2 = QFrame(self.panelKiri)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(15, 352, 310, 250))
        self.frame_2.setStyleSheet(u"QFrame { background-color: #0f3460; border-radius: 12px; border: 1px solid #1e4d7b; }")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.labelKontrolTitle = QLabel(self.frame_2)
        self.labelKontrolTitle.setObjectName(u"labelKontrolTitle")
        self.labelKontrolTitle.setGeometry(QRect(15, 10, 200, 22))
        self.labelKontrolTitle.setStyleSheet(u"color: #00c85d; font-size: 10px; font-weight: bold; letter-spacing: 2px; background: transparent; border: none;")
        self.inputSearch = QLineEdit(self.frame_2)
        self.inputSearch.setObjectName(u"inputSearch")
        self.inputSearch.setGeometry(QRect(15, 40, 240, 34))
        self.inputSearch.setStyleSheet(u"QLineEdit { background-color: #0a1930; color: #ffffff; border: 1px solid #1e4d7b; border-radius: 10px; padding: 4px 14px; font-size: 11px; } QLineEdit:focus { border: 1px solid #00c85d; }")
        self.btnSearch = QPushButton(self.frame_2)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(260, 40, 34, 34))
        self.btnSearch.setMinimumSize(QSize(34, 34))
        self.btnSearch.setMaximumSize(QSize(34, 34))
        self.btnSearch.setStyleSheet(u"QPushButton { background-color: #ffd60a; color: #000; border-radius: 10px; font-size: 11px; font-weight: bold; border: none; } QPushButton:hover { background-color: #00ff87; } QPushButton:pressed { background-color: #e6c000; }")
        self.comboSort = QComboBox(self.frame_2)
        self.comboSort.addItem("")
        self.comboSort.addItem("")
        self.comboSort.addItem("")
        self.comboSort.setObjectName(u"comboSort")
        self.comboSort.setGeometry(QRect(15, 86, 185, 34))
        self.comboSort.setStyleSheet(u"QComboBox { background-color: #0a1930; color: #ffffff; border: 1px solid #1e4d7b; border-radius: 10px; padding: 4px 14px; font-size: 11px; } QComboBox:focus { border: 1px solid #00c85d; } QComboBox::drop-down { border: none; width: 20px; } QComboBox QAbstractItemView { background-color: #0f3460; color: #ffffff; selection-background-color: #009944; border: 1px solid #1e4d7b; }")
        self.btnSort = QPushButton(self.frame_2)
        self.btnSort.setObjectName(u"btnSort")
        self.btnSort.setGeometry(QRect(208, 86, 86, 34))
        self.btnSort.setStyleSheet(u"QPushButton { background-color: #0a1930; color: #ffd60a; border-radius: 10px; font-size: 11px; font-weight: bold; border: 1px solid #ffd60a; } QPushButton:hover { background-color: #ffd60a; color: #000; } QPushButton:pressed { background-color: #e6c000; }")
        self.btnDisplay = QPushButton(self.frame_2)
        self.btnDisplay.setObjectName(u"btnDisplay")
        self.btnDisplay.setGeometry(QRect(15, 132, 279, 34))
        self.btnDisplay.setStyleSheet(u"QPushButton { background-color: #0a1930; color: #00ff87; border-radius: 10px; font-size: 11px; font-weight: bold; letter-spacing: 1px; border: 1px solid #00c85d; } QPushButton:hover { background-color: #00c85d; color: #000; } QPushButton:pressed { background-color: #009944; }")
        self.btnDeleteGlobal = QPushButton(self.frame_2)
        self.btnDeleteGlobal.setObjectName(u"btnDeleteGlobal")
        self.btnDeleteGlobal.setGeometry(QRect(15, 178, 279, 34))
        self.btnDeleteGlobal.setStyleSheet(u"QPushButton { background-color: #e63946; color: white; border-radius: 10px; font-size: 11px; font-weight: bold; letter-spacing: 1px; border: none; } QPushButton:hover { background-color: #ff6b6b; } QPushButton:pressed { background-color: #c1121f; }")
        self.btnPrevious = QPushButton(self.frame_2)
        self.btnPrevious.setObjectName(u"btnPrevious")
        self.btnPrevious.setGeometry(QRect(15, 222, 130, 18))
        self.btnPrevious.setStyleSheet(u"QPushButton { background-color: transparent; color: #ffd60a; border-radius: 8px; font-size: 10px; font-weight: bold; border: 1px solid #ffd60a; } QPushButton:hover { background-color: #ffd60a; color: #000; }")
        self.btnNext = QPushButton(self.frame_2)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(163, 222, 131, 18))
        self.btnNext.setStyleSheet(u"QPushButton { background-color: transparent; color: #ffd60a; border-radius: 8px; font-size: 10px; font-weight: bold; border: 1px solid #ffd60a; } QPushButton:hover { background-color: #ffd60a; color: #000; }")
        self.labelPauseIcon = QLabel(self.panelKiri)
        self.labelPauseIcon.setObjectName(u"labelPauseIcon")
        self.labelPauseIcon.setGeometry(QRect(0, 0, 0, 0))
        self.labelLogoSonara = QLabel(self.panelKiri)
        self.labelLogoSonara.setObjectName(u"labelLogoSonara")
        self.labelLogoSonara.setGeometry(QRect(0, 0, 0, 0))

        self.horizontalLayout.addWidget(self.panelKiri)

        self.panelKanan = QWidget(self.centralwidget)
        self.panelKanan.setObjectName(u"panelKanan")
        self.panelKanan.setStyleSheet(u"background-color: #1a1a2e;")
        self.labelPlaylistHeader = QLabel(self.panelKanan)
        self.labelPlaylistHeader.setObjectName(u"labelPlaylistHeader")
        self.labelPlaylistHeader.setGeometry(QRect(20, 18, 400, 28))
        self.labelPlaylistHeader.setStyleSheet(u"color: #ffffff; font-size: 14px; font-weight: bold; letter-spacing: 2px; background: transparent;")
        self.labelPlaylistSub = QLabel(self.panelKanan)
        self.labelPlaylistSub.setObjectName(u"labelPlaylistSub")
        self.labelPlaylistSub.setGeometry(QRect(22, 46, 400, 16))
        self.labelPlaylistSub.setStyleSheet(u"color: #a0a0b0; font-size: 10px; background: transparent;")
        self.lineRight = QFrame(self.panelKanan)
        self.lineRight.setObjectName(u"lineRight")
        self.lineRight.setGeometry(QRect(20, 66, 520, 2))
        self.lineRight.setStyleSheet(u"background-color: #1e4d7b; border: none;")
        self.lineRight.setFrameShape(QFrame.Shape.HLine)
        self.tablePlaylist = QTableWidget(self.panelKanan)
        if (self.tablePlaylist.columnCount() < 6):
            self.tablePlaylist.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.tablePlaylist.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tablePlaylist.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tablePlaylist.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tablePlaylist.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tablePlaylist.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tablePlaylist.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.tablePlaylist.setObjectName(u"tablePlaylist")
        self.tablePlaylist.setGeometry(QRect(15, 78, 535, 470))
        self.tablePlaylist.setStyleSheet(u"QTableWidget { background-color: #112240; color: #ffffff; border: 1px solid #1e4d7b; border-radius: 10px; gridline-color: #1e4d7b; font-size: 11px; outline: none; } QTableWidget::item { padding: 6px 8px; border-bottom: 1px solid #1e4d7b; } QTableWidget::item:selected { background-color: #009944; color: white; } QTableWidget::item:alternate { background-color: #0a1930; } QHeaderView::section { background-color: #0d2137; color: #00c85d; font-size: 10px; font-weight: bold; letter-spacing: 1px; padding: 8px 6px; border: none; border-bottom: 2px solid #00c85d; border-right: 1px solid #1e4d7b; } QScrollBar:vertical { background: #0d2137; width: 8px; border-radius: 4px; } QScrollBar::handle:vertical { background: #009944; border-radius: 4px; }")
        self.tablePlaylist.setAlternatingRowColors(True)
        self.tablePlaylist.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tablePlaylist.setShowGrid(True)
        self.labelTagline = QLabel(self.panelKanan)
        self.labelTagline.setObjectName(u"labelTagline")
        self.labelTagline.setGeometry(QRect(15, 556, 535, 30))
        self.labelTagline.setStyleSheet(u"color: #00ff87; font-size: 13px; font-weight: bold; letter-spacing: 3px; background: transparent;")
        self.labelTagline.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelSubTagline = QLabel(self.panelKanan)
        self.labelSubTagline.setObjectName(u"labelSubTagline")
        self.labelSubTagline.setGeometry(QRect(15, 585, 535, 18))
        self.labelSubTagline.setStyleSheet(u"color: #a0a0b0; font-size: 10px; background: transparent;")
        self.labelSubTagline.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelImageHeadphone = QLabel(self.panelKanan)
        self.labelImageHeadphone.setObjectName(u"labelImageHeadphone")
        self.labelImageHeadphone.setGeometry(QRect(0, 0, 0, 0))

        self.horizontalLayout.addWidget(self.panelKanan)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 900, 30))
        self.menubar.setStyleSheet(u"QMenuBar { background-color: #16213e; color: #a0a0b0; border-bottom: 1px solid #1e4d7b; font-size: 11px; } QMenuBar::item:selected { background-color: #0f3460; color: #00c85d; }")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"QStatusBar { background-color: #16213e; color: #a0a0b0; font-size: 10px; border-top: 1px solid #1e4d7b; }")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SONARA \u2014 Playlist Manager", None))
        self.labelTitle.setText(QCoreApplication.translate("MainWindow", u"SONARA", None))
        self.labelSubtitle.setText(QCoreApplication.translate("MainWindow", u"PLAYLIST MANAGER", None))
        self.labelFormTitle.setText(QCoreApplication.translate("MainWindow", u"+ TAMBAH LAGU", None))
        self.labelInputJudul.setText(QCoreApplication.translate("MainWindow", u"JUDUL LAGU", None))
        self.inputJudul.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Judul lagu...", None))
        self.labelInputPenyanyi.setText(QCoreApplication.translate("MainWindow", u"PENYANYI", None))
        self.inputPenyanyi.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nama penyanyi...", None))
        self.labelInputDurasi.setText(QCoreApplication.translate("MainWindow", u"DURASI", None))
        self.inputDurasi.setPlaceholderText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.labelInputGenre.setText(QCoreApplication.translate("MainWindow", u"GENRE", None))
        self.inputGenre.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Genre musik...", None))
        self.btnInsertLagu.setText(QCoreApplication.translate("MainWindow", u"+ INSERT LAGU", None))
        self.labelKontrolTitle.setText(QCoreApplication.translate("MainWindow", u"KONTROL", None))
        self.inputSearch.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Cari lagu...", None))
        self.btnSearch.setText(QCoreApplication.translate("MainWindow", u"Go", None))
        self.comboSort.setItemText(0, QCoreApplication.translate("MainWindow", u"Judul (A-Z)", None))
        self.comboSort.setItemText(1, QCoreApplication.translate("MainWindow", u"Penyanyi", None))
        self.comboSort.setItemText(2, QCoreApplication.translate("MainWindow", u"Genre", None))

        self.btnSort.setText(QCoreApplication.translate("MainWindow", u"SORT", None))
        self.btnDisplay.setText(QCoreApplication.translate("MainWindow", u"DISPLAY SEMUA LAGU", None))
        self.btnDeleteGlobal.setText(QCoreApplication.translate("MainWindow", u"DELETE LAGU DIPILIH", None))
        self.btnPrevious.setText(QCoreApplication.translate("MainWindow", u"< PREVIOUS", None))
        self.btnNext.setText(QCoreApplication.translate("MainWindow", u"NEXT >", None))
        self.labelPauseIcon.setText("")
        self.labelLogoSonara.setText("")
        self.labelPlaylistHeader.setText(QCoreApplication.translate("MainWindow", u"DAFTAR PLAYLIST", None))
        self.labelPlaylistSub.setText(QCoreApplication.translate("MainWindow", u"Kelola lagu favoritmu di sini", None))
        ___qtablewidgetitem = self.tablePlaylist.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"No", None))
        ___qtablewidgetitem1 = self.tablePlaylist.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Judul", None))
        ___qtablewidgetitem2 = self.tablePlaylist.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Penyanyi", None))
        ___qtablewidgetitem3 = self.tablePlaylist.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Durasi", None))
        ___qtablewidgetitem4 = self.tablePlaylist.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Genre", None))
        ___qtablewidgetitem5 = self.tablePlaylist.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Aksi", None))
        self.labelTagline.setText(QCoreApplication.translate("MainWindow", u"NIKMATI MUSIKMU", None))
        self.labelSubTagline.setText(QCoreApplication.translate("MainWindow", u"Anggap aja Spotify woilah cik", None))
        self.labelImageHeadphone.setText("")
    # retranslateUi

